Optimize file CI.yml

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -2,9 +2,7 @@ name: Build & Integration Test Notes App
 
 on:
   push:
-    branches:
-      - main
-      - "feature/**"
+    branches: [ "main", "feature/**" ]
 
 jobs:
   build-and-test:
@@ -14,41 +12,6 @@ jobs:
       run:
         working-directory: ./notesWeb
         
-    env:
-      # App
-      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
-
-      # Database
-      DB_URL: ${{ secrets.DB_URL }}
-      DB_USERNAME: ${{ secrets.DB_USERNAME }}
-      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
-
-      # JWT
-      JWT_SECRET: ${{ secrets.JWT_SECRET }}
-      JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
-
-      # Redis
-      REDIS_HOST: ${{ secrets.REDIS_HOST }}
-      REDIS_PORT: ${{ secrets.REDIS_PORT }}
-
-      # Kafka
-      KAFKA_BOOTSTRAP_SERVERS: ${{ secrets.KAFKA_BOOTSTRAP_SERVERS }}
-
-      # RabbitMQ
-      RABBIT_HOST: ${{ secrets.RABBIT_HOST }}
-      RABBIT_PORT: ${{ secrets.RABBIT_PORT }}
-      RABBIT_USERNAME: ${{ secrets.RABBIT_USERNAME }}
-      RABBIT_PASSWORD: ${{ secrets.RABBIT_PASSWORD }}
-      RABBIT_STOMP_PORT: ${{ secrets.RABBIT_STOMP_PORT }}
-
-      # Cloudinary
-      CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
-      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
-      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
-
-      # Image version
-      APP_VERSION: ${{ github.sha }}
-
     steps:
       - name: Checkout source
         uses: actions/checkout@v4
@@ -58,49 +21,97 @@ jobs:
         with:
           java-version: '21'
           distribution: 'temurin'
+          cache: 'maven' #Caching Maven dependencies for faster builds
 
-      - name: Build Spring Boot
+      - name: Build with Maven
         run: ./mvnw clean package -DskipTests
 
-      - name: Build Docker image (Local)
-        run: docker build -t ${{ env.DOCKERHUB_USERNAME }}/notes-app:${{ env.APP_VERSION }} .
-
-      - name: Start Services & Integration Test
-        run: |
-          docker compose up -d
-          echo "Waiting for service to be healthy..."
-          sleep 60 
-
-      - name: Check Swagger API
-        run: |
-          status_code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8081/v3/api-docs)
-          if [ $status_code -eq 200 ]; then
-            echo "Swagger is ok!"
-          else
-            echo "Integration Test Failed with status $status_code"
-            docker compose logs notes-app
-            exit 1
-          fi
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3 #Optimize -> use for managing build images and caching
 
       - name: Login DockerHub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
+      - name: Build and Push SHA Image
+        uses: docker/build-push-action@v5
+        with:
+          context: ./notesWeb
+          push: true
+          tags: ${{ secrets.DOCKERHUB_USERNAME }}/notes-app:${{ github.sha }}
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
 
-      - name: Push Docker image
+      - name: Start Services & Integration Test
+        env:
+        # App
+         DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
+
+        # Database
+         DB_URL: ${{ secrets.DB_URL }}
+         DB_USERNAME: ${{ secrets.DB_USERNAME }}
+         DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
+
+        # JWT
+         JWT_SECRET: ${{ secrets.JWT_SECRET }}
+         JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
+
+        # Redis
+         REDIS_HOST: ${{ secrets.REDIS_HOST }}
+         REDIS_PORT: ${{ secrets.REDIS_PORT }}
+
+        # Kafka
+         KAFKA_BOOTSTRAP_SERVERS: ${{ secrets.KAFKA_BOOTSTRAP_SERVERS }}
+
+        # RabbitMQ
+         RABBIT_HOST: ${{ secrets.RABBIT_HOST }}
+         RABBIT_PORT: ${{ secrets.RABBIT_PORT }}
+         RABBIT_USERNAME: ${{ secrets.RABBIT_USERNAME }}
+         RABBIT_PASSWORD: ${{ secrets.RABBIT_PASSWORD }}
+         RABBIT_STOMP_PORT: ${{ secrets.RABBIT_STOMP_PORT }}
+
+        # Cloudinary
+         CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
+         CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
+         CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
+
+        # Image version
+         APP_VERSION: ${{ github.sha }}
+
         run: |
-          docker push ${{ env.DOCKERHUB_USERNAME }}/notes-app:${{ env.APP_VERSION }}
+          docker compose up -d 
+          echo "Waiting for service to be healthy..."
+          #Loop check Swagger
+          for i in {1..20}; do
+            if curl -s -o /dev/null -w "%{http_code}" http://localhost:8081/v3/api-docs | grep -q "200"; then
+              echo "Swagger is up & running!"
+              exit 0
+            fi
+            echo "Waiting for api.. ($i/20)"
+            sleep 5
+          done
+          echo "Integration test failed!"
+          docker compose logs notes-app
+          exit 1
+
+      - name: Promote Image to Branch Tag
+        if: success()
+        run: |
+          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/notes-app
+          SHA_TAG=${{ github.sha }}
           
           if [ "${{ github.ref }}" == "refs/heads/main" ]; then
-             echo "Currently on the main branch -> Push the latest version"
-             docker tag ${{ env.DOCKERHUB_USERNAME }}/notes-app:${{ env.APP_VERSION }} ${{ env.DOCKERHUB_USERNAME }}/notes-app:latest
-             docker push ${{ env.DOCKERHUB_USERNAME }}/notes-app:latest
+            echo "Promoting to LATEST"
+            docker pull $IMAGE_NAME:$SHA_TAG
+            docker tag $IMAGE_NAME:$SHA_TAG $IMAGE_NAME:latest
+            docker push $IMAGE_NAME:latest
           else
-             BRANCH_NAME=$(echo ${{ github.ref_name }} | sed 's/\//-/g')
-             echo "Currently on the feature branch -> Push the tag: feature-$BRANCH_NAME"
-             docker tag ${{ env.DOCKERHUB_USERNAME }}/notes-app:${{ env.APP_VERSION }} ${{ env.DOCKERHUB_USERNAME }}/notes-app:feature-$BRANCH_NAME
-             docker push ${{ env.DOCKERHUB_USERNAME }}/notes-app:feature-$BRANCH_NAME
+            CLEAN_BRANCH=$(echo ${{ github.ref_name }} | sed 's/\//-/g')
+            echo "Promoting to feature-$CLEAN_BRANCH"
+            docker pull $IMAGE_NAME:$SHA_TAG
+            docker tag $IMAGE_NAME:$SHA_TAG $IMAGE_NAME:feature-$CLEAN_BRANCH
+            docker push $IMAGE_NAME:feature-$CLEAN_BRANCH
           fi
 
       - name: Shutdown
